language: node_js
node_js:
  - "6.4"
before_install:
  - npm install -g yarn --cache-min 999999999
install:
  - yarn
script:
  -  "npm run lint"
  -  "npm test"
after_success:
  - bash <(curl -s https://codecov.io/bash)